version: '3'

vars:
  UID:
    sh: id -u
  GID:
    sh: id -g

tasks:
  # 新規プロジェクト用: Vite+React+TS を初期化
  create-project:
    desc: "Vite React+TS プロジェクトを初期化"
    cmds:
      - mkdir -p frontend
      - >
        docker run --rm
        -v {{.PWD}}/frontend:/workspace
        -w /workspace
        -u {{.UID}}:{{.GID}}
        node:22-alpine
        sh -c "npm create vite@latest . -- --template react-ts"
      - task: setup-vite-config
      - task: install
      - task: up
    status:
      - test -f frontend/package.json

  setup-vite-config:
    desc: "Vite の開発サーバー設定を上書き"
    cmds:
      - |
        cat > frontend/vite.config.ts << 'EOF'
        import { defineConfig } from 'vite'
        import react from '@vitejs/plugin-react'

        export default defineConfig({
          plugins: [react()],
          server: {
            host: '0.0.0.0',
            port: 5173,
            watch: {
              usePolling: true,
            },
          },
        })
        EOF

  # 依存インストール + コンテナ起動
  install:
    desc: "依存関係をコンテナ内でインストール"
    cmds:
      - docker compose run --rm app npm install

  up:
    desc: "Dockerコンテナをバックグラウンドで起動"
    cmds:
      - docker compose up --detach

  down:
    desc: "Dockerコンテナを停止して削除"
    cmds:
      - docker compose down

  stop:
    desc: "コンテナを停止（削除はしない）"
    cmds:
      - docker compose stop

  ps:
    desc: "コンテナの状態を表示"
    cmds:
      - docker compose ps

  app:
    desc: "app コンテナにシェルで入る"
    cmds:
      - docker compose exec app sh

  logs:
    desc: "app コンテナのログを表示"
    cmds:
      - docker compose logs -f app

  clean:
    desc: "frontend ディレクトリを削除（プロジェクトを消す）"
    cmds:
      - rm -rf frontend
    prompt: "frontend ディレクトリを削除しますか？"

  destroy:
    desc: "Docker のコンテナ・イメージ・ボリュームを全削除"
    cmds:
      - docker compose down --rmi all --volumes --remove-orphans
    prompt: "イメージやボリュームも含めて完全に削除します。よろしいですか？"

  remake:
    desc: "完全初期化してプロジェクトを作り直す"
    cmds:
      - task: clean
      - task: destroy
      - task: create-project
